# Generated by Django 2.0.5 on 2018-11-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_auto_20181029_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlol',
            name='e_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_varsitysubscriptions',
            field=models.IntegerField(null=True),
        ),
    ]
