# Generated by Django 2.0.5 on 2018-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_varsity_v_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
