# Generated by Django 2.0.5 on 2018-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_auto_20181202_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_varsitysubscriptions',
        ),
        migrations.AddField(
            model_name='user',
            name='u_varsitysubscriptions',
            field=models.ManyToManyField(null=True, to='websites.varsity'),
        ),
    ]
