# Generated by Django 2.0.5 on 2018-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_auto_20181214_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_varsitysubscriptions',
            field=models.ManyToManyField(to='websites.varsity'),
        ),
    ]
