# Generated by Django 2.0.5 on 2018-12-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_auto_20181214_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='varsity',
            name='v_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
